// Lista de todos os aplicativos que você quer que seja gerado..
export const appList = [
    'comercialexpress',
    'mastterdelivery',
    'papas',
    'speedmotofrete',
    'boydry',
    'callboy',
    'novacobretudo',
    'dobrasil',
    'entregasimediato',
    'lijet',
    'mtlogg',
    'maualog',
    'netboy',
    'packman',
    'celereexpress',
    'disktudo',
    'famotoboys',
    'maltalog',
    'postarlog',
    'speedmotoboy',
    'sullogistica',
    'direcaoexpress',
    'kftransporte',
    'pakot',
    'scriptport',
    'coperboy',
    'dedexexpress',
    'motoboybelem',
    'suaentrega',
    'tjlexpress',
    'flexpress',
    'leveelog',
    'schnell',
    'selectdelivery',
    'surfsentregas',
    'altalogexpress',
    'dedexexpress',
    'eduardomotoboys',
    'expressogrimm',
    'aclog',
    'vidaexpress',
    'beltraoexpress',
    'f5delivery',
    'ramosserviceexpress',
    'startentregas',
    'vasto',
    'levodelivery',
    'logligeiro',
    'mercadofeito',
    'uniosentregas',
    'zfdeliveryfast',
    'beraldomotoboy',
    'gtexpress',
    'racingexpress',
    'fly',
    'titanexpress',
    'gp46express',
    'tbtexpress',
    'trbexpressrj',
    'dcomotoboy',
    'papatempo',
    'araujoexpress',
    'embuexpress',
    'iceboys',
    'logmoto',
    'vipfast',
    '2fexpress',
    'bluedelivery',
    'deliverymanausexpress',
    'diferencialmotoexpress',
    'rota66encomendas',
    'djexpress',
    'hortoboy',
    'rapidyexpress',
    // 'g3logistica', sem info, nao pode publicar na loja
    // 'bfstransportes', nao pode publicar na loja
    // 'pecexpress', sem info, nao pode publicar na loja
    // 'sharklogistica', sem info, nao pode publicar na loja
    // 'mjmotoboy', sem info, nao pode publicar na loja
    // 'noizentrega', sem info, nao pode publicar na loja
    // 'andrademotoexpress', nao pode publicar na loja
    // 'tomexpress', CLIENTE NAO ESTA USANDO NO MOMENTO, nao pode publicar na loja
    // 'flpsp', nao pode publicar na loja
];