// Lista de todos os aplicativos que você quer que seja gerado..
export const appList = [
    '2fexpress',
    'aclog',
    'altalogexpress',
    'andrademotoexpress', // Precisa ser publicado
    'araujoexpress',
    'beltraoexpress',
    'beraldomotoboy',
    'bfstransportes', // Precisa ser publicado
    'bluedelivery',
    'boydry',
    'callboy',
    'celereexpress',
    'comercialexpress',
    'coperboy',
    'dcomotoboy',
    'dedexexpress',
    'dedexexpress',
    'deliverymanausexpress',
    'diferencialmotoexpress',
    'direcaoexpress',
    'disktudo',
    'djexpress',
    'dobrasil',
    'eduardomotoboys',
    'embuexpress',
    'entregasimediato',
    'expressogrimm',
    'f5delivery',
    'famotoboys',
    'flexpress',
    'flpsp', // Precisa ser publicado
    'fly',
    'g3logistica', // Precisa ser publicado
    'gp46express',
    'gtexpress',
    'hortoboy',
    'iceboys',
    'kftransporte',
    'leveelog',
    'levodelivery',
    'lijet',
    'logligeiro',
    'logmoto',
    'maltalog',
    'mastterdelivery',
    'maualog',
    'mercadofeito',
    'motoboybelem',
    'mtlogg',
    'netboy',
    'noizentrega', // Precisa ser publicado
    'novacobretudo',
    'packman',
    'pakot',
    'papas',
    'papatempo',
    'postarlog',
    'racingexpress',
    'ramosserviceexpress',
    'rapidyexpress',
    'rota66encomendas',
    'schnell',
    'scriptport',
    'selectdelivery',
    'sharklogistica', // Precisa ser publicado
    'speedmotoboy',
    'speedmotofrete',
    'startentregas',
    'suaentrega',
    'sullogistica',
    'surfsentregas',
    'tbtexpress',
    'titanexpress',
    'tjlexpress',
    'trbexpressrj',
    'uniosentregas',
    'uniosfranca', // Precisam ser publicado
    'vasto',
    'vidaexpress',
    'vipfast',
    'zfdeliveryfast'
];