// Lista de todos os aplicativos que você quer que seja gerado..
export const appList = [
    'comercialexpress',
    'mastterdelivery',
    'papas',
    'speedmotofrete',
    'boydry',
    'callboy',
    'novacobretudo',
    'dobrasil',
    'entregasimediato',
    'flpsp',
    'lijet',
    'mtlogg',
    'maualog',
    'netboy',
    'packman',
    'celereexpress',
    'disktudo',
    'famotoboys',
    'maltalog',
    'postarlog',
    'speedmotoboy',
    'sullogistica',
    'direcaoexpress',
    'kftransporte',
    'pakot',
    'scriptport',
    // 'tomexpress', CLIENTE NAO ESTA USANDO NO MOMENTO
    'coperboy',
    'dedexexpress',
    'motoboybelem',
    'suaentrega',
    'tjlexpress',
    'flexpress',
    'leveelog',
    'schnell',
    'selectdelivery',
    // 'surfsentregas', VERIFICAR PQ DEU PROBLEMA
    'altalogexpress',
    'dedexexpress',
    'eduardomotoboys',
    'expressogrimm',
    'aclog',
    'vidaexpress',
    'beltraoexpress',
    'f5delivery',
    'ramosserviceexpress',
    'startentregas',
    'vasto',
    'levodelivery',
    'logligeiro',
    'mercadofeito',
    'uniosentregas',
    'zfdeliveryfast',
    'andrademotoexpress',
    'beraldomotoboy',
    'gtexpress',
    // 'noizentrega', sem info
    'racingexpress',
    'fly',
    'titanexpress',
    'gp46express',
    'tbtexpress',
    'trbexpressrj',
    'dcomotoboy',
    // 'mjmotoboy', sem info
    'papatempo',
    // 'pecexpress', sem info
    // 'sharklogistica', sem info
    'araujoexpress',
    'embuexpress',
    'iceboys',
    'logmoto',
    'vipfast',
    '2fexpress',
    'bluedelivery',
    'deliverymanausexpress',
    'diferencialmotoexpress',
    'rota66encomendas',
    'bfstransportes',
    'djexpress',
    // 'g3logistica', sem info
    'hortoboy',
    'rapidyexpress',
]